/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ProvenanceResponse } from '../../models/provenance-response';

export interface GetDomainProvenance$Params {
  domainEntityId: string;
}

export function getDomainProvenance(http: HttpClient, rootUrl: string, params: GetDomainProvenance$Params, context?: HttpContext): Observable<StrictHttpResponse<ProvenanceResponse>> {
  const rb = new RequestBuilder(rootUrl, getDomainProvenance.PATH, 'get');
  if (params) {
    rb.path('domainEntityId', params.domainEntityId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ProvenanceResponse>;
    })
  );
}

getDomainProvenance.PATH = '/api/v1/domain/{domainEntityId}/provenance';
