/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImportResponse } from '../../models/import-response';

export interface GetImport$Params {
  id: string;
}

export function getImport(http: HttpClient, rootUrl: string, params: GetImport$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportResponse>> {
  const rb = new RequestBuilder(rootUrl, getImport.PATH, 'get');
  if (params) {
    rb.path('id', params.id, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImportResponse>;
    })
  );
}

getImport.PATH = '/api/v1/imports/{id}';
