/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { ImportCreatedResponse } from '../../models/import-created-response';
import { JsonElement } from '../../models/json-element';

export interface ImportBundle$Params {
  sourceSystemLabel?: string;
  fileName?: string;
      body: JsonElement
}

export function importBundle(http: HttpClient, rootUrl: string, params: ImportBundle$Params, context?: HttpContext): Observable<StrictHttpResponse<ImportCreatedResponse>> {
  const rb = new RequestBuilder(rootUrl, importBundle.PATH, 'post');
  if (params) {
    rb.query('sourceSystemLabel', params.sourceSystemLabel, {});
    rb.query('fileName', params.fileName, {});
    rb.body(params.body, 'application/json');
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<ImportCreatedResponse>;
    })
  );
}

importBundle.PATH = '/api/v1/imports';
