<Project Sdk="Microsoft.NET.Sdk.Web">

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Scalar.AspNetCore" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="../OncoBridge.Application/OncoBridge.Application.csproj" />
    <ProjectReference Include="../OncoBridge.Infrastructure/OncoBridge.Infrastructure.csproj" />
    <ProjectReference Include="../OncoBridge.Interop.Fhir/OncoBridge.Interop.Fhir.csproj" />
  </ItemGroup>

</Project>
