// <auto-generated />
using System;
using System.Collections.Generic;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OncoBridge.Infrastructure.Persistence;

#nullable disable

namespace OncoBridge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OncoBridgeDbContext))]
    [Migration("20260816011523_CanonicalNormalizationSchema")]
    partial class CanonicalNormalizationSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OncoBridge.Domain.Oncology.CancerStaging", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.Property<Guid>("PrimaryCancerDiagnosisId")
                        .HasColumnType("uuid")
                        .HasColumnName("primary_cancer_diagnosis_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Effective", "OncoBridge.Domain.Oncology.CancerStaging.Effective#PartialDate", b1 =>
                        {
                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("effective_day");

                            b1.Property<string>("Instant")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("effective_instant");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("effective_month");

                            b1.Property<string>("Precision")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("effective_precision");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("effective_year");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Method", "OncoBridge.Domain.Oncology.CancerStaging.Method#StagingMethod", b1 =>
                        {
                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("method_kind");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Code", "OncoBridge.Domain.Oncology.CancerStaging.Method#StagingMethod.Code#CodedConcept", b2 =>
                                {
                                    b2.IsRequired();

                                    b2.Property<string>("Code")
                                        .IsRequired()
                                        .HasMaxLength(200)
                                        .HasColumnType("character varying(200)")
                                        .HasColumnName("method_code");

                                    b2.Property<string>("Display")
                                        .HasMaxLength(1000)
                                        .HasColumnType("character varying(1000)")
                                        .HasColumnName("method_display");

                                    b2.Property<string>("System")
                                        .IsRequired()
                                        .HasMaxLength(500)
                                        .HasColumnType("character varying(500)")
                                        .HasColumnName("method_system");
                                });

                            b1.HasDiscriminator<string>("Discriminator").HasValue("StagingMethod");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "StageGroup", "OncoBridge.Domain.Oncology.CancerStaging.StageGroup#CodedConcept", b1 =>
                        {
                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("stage_group_code");

                            b1.Property<string>("Display")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("stage_group_display");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("stage_group_system");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_cancer_staging_batch_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_cancer_staging_patient_id");

                    b.HasIndex("PrimaryCancerDiagnosisId")
                        .HasDatabaseName("ix_cancer_staging_primary_cancer_diagnosis_id");

                    b.ToTable("cancer_staging", (string)null);
                });

            modelBuilder.Entity("OncoBridge.Domain.Oncology.CancerSurgicalProcedure", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BodySite", "OncoBridge.Domain.Oncology.CancerSurgicalProcedure.BodySite#CodedConcept", b1 =>
                        {
                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("body_site_code");

                            b1.Property<string>("Display")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("body_site_display");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("body_site_system");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Code", "OncoBridge.Domain.Oncology.CancerSurgicalProcedure.Code#CodedConcept", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("code_code");

                            b1.Property<string>("Display")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("code_display");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("code_system");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Performed", "OncoBridge.Domain.Oncology.CancerSurgicalProcedure.Performed#TemporalOccurrence", b1 =>
                        {
                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("performed_kind");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Date", "OncoBridge.Domain.Oncology.CancerSurgicalProcedure.Performed#TemporalOccurrence.Date#PartialDate", b2 =>
                                {
                                    b2.Property<int?>("Day")
                                        .HasColumnType("integer")
                                        .HasColumnName("performed_date_day");

                                    b2.Property<string>("Instant")
                                        .HasMaxLength(40)
                                        .HasColumnType("character varying(40)")
                                        .HasColumnName("performed_date_instant");

                                    b2.Property<int?>("Month")
                                        .HasColumnType("integer")
                                        .HasColumnName("performed_date_month");

                                    b2.Property<string>("Precision")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("performed_date_precision");

                                    b2.Property<int>("Year")
                                        .HasColumnType("integer")
                                        .HasColumnName("performed_date_year");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Period", "OncoBridge.Domain.Oncology.CancerSurgicalProcedure.Performed#TemporalOccurrence.Period#PartialPeriod", b2 =>
                                {
                                    b2.Property<string>("Discriminator")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("performed_period_kind");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "End", "OncoBridge.Domain.Oncology.CancerSurgicalProcedure.Performed#TemporalOccurrence.Period#PartialPeriod.End#PartialDate", b3 =>
                                        {
                                            b3.Property<int?>("Day")
                                                .HasColumnType("integer")
                                                .HasColumnName("performed_end_day");

                                            b3.Property<string>("Instant")
                                                .HasMaxLength(40)
                                                .HasColumnType("character varying(40)")
                                                .HasColumnName("performed_end_instant");

                                            b3.Property<int?>("Month")
                                                .HasColumnType("integer")
                                                .HasColumnName("performed_end_month");

                                            b3.Property<string>("Precision")
                                                .IsRequired()
                                                .HasMaxLength(20)
                                                .HasColumnType("character varying(20)")
                                                .HasColumnName("performed_end_precision");

                                            b3.Property<int>("Year")
                                                .HasColumnType("integer")
                                                .HasColumnName("performed_end_year");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Start", "OncoBridge.Domain.Oncology.CancerSurgicalProcedure.Performed#TemporalOccurrence.Period#PartialPeriod.Start#PartialDate", b3 =>
                                        {
                                            b3.Property<int?>("Day")
                                                .HasColumnType("integer")
                                                .HasColumnName("performed_start_day");

                                            b3.Property<string>("Instant")
                                                .HasMaxLength(40)
                                                .HasColumnType("character varying(40)")
                                                .HasColumnName("performed_start_instant");

                                            b3.Property<int?>("Month")
                                                .HasColumnType("integer")
                                                .HasColumnName("performed_start_month");

                                            b3.Property<string>("Precision")
                                                .IsRequired()
                                                .HasMaxLength(20)
                                                .HasColumnType("character varying(20)")
                                                .HasColumnName("performed_start_precision");

                                            b3.Property<int>("Year")
                                                .HasColumnType("integer")
                                                .HasColumnName("performed_start_year");
                                        });

                                    b2.HasDiscriminator<string>("Discriminator").HasValue("PartialPeriod");
                                });

                            b1.HasDiscriminator<string>("Discriminator").HasValue("TemporalOccurrence");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_cancer_surgical_procedure_batch_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_cancer_surgical_procedure_patient_id");

                    b.ToTable("cancer_surgical_procedure", (string)null);
                });

            modelBuilder.Entity("OncoBridge.Domain.Oncology.Patient", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("SourceIdentifier")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_identifier");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BirthDate", "OncoBridge.Domain.Oncology.Patient.BirthDate#PartialDate", b1 =>
                        {
                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("birth_date_day");

                            b1.Property<string>("Instant")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("birth_date_instant");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("birth_date_month");

                            b1.Property<string>("Precision")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("birth_date_precision");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("birth_date_year");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "SexAtBirthAsRecorded", "OncoBridge.Domain.Oncology.Patient.SexAtBirthAsRecorded#CodedConcept", b1 =>
                        {
                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("sex_at_birth_code");

                            b1.Property<string>("Display")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("sex_at_birth_display");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("sex_at_birth_system");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_patient_batch_id");

                    b.ToTable("patient", (string)null);
                });

            modelBuilder.Entity("OncoBridge.Domain.Oncology.PrimaryCancerDiagnosis", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<Guid>("PatientId")
                        .HasColumnType("uuid")
                        .HasColumnName("patient_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "BodySite", "OncoBridge.Domain.Oncology.PrimaryCancerDiagnosis.BodySite#CodedConcept", b1 =>
                        {
                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("body_site_code");

                            b1.Property<string>("Display")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("body_site_display");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("body_site_system");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Code", "OncoBridge.Domain.Oncology.PrimaryCancerDiagnosis.Code#CodedConcept", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("code_code");

                            b1.Property<string>("Display")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("code_display");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("code_system");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Onset", "OncoBridge.Domain.Oncology.PrimaryCancerDiagnosis.Onset#TemporalOccurrence", b1 =>
                        {
                            b1.Property<string>("Discriminator")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("onset_kind");

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Date", "OncoBridge.Domain.Oncology.PrimaryCancerDiagnosis.Onset#TemporalOccurrence.Date#PartialDate", b2 =>
                                {
                                    b2.Property<int?>("Day")
                                        .HasColumnType("integer")
                                        .HasColumnName("onset_date_day");

                                    b2.Property<string>("Instant")
                                        .HasMaxLength(40)
                                        .HasColumnType("character varying(40)")
                                        .HasColumnName("onset_date_instant");

                                    b2.Property<int?>("Month")
                                        .HasColumnType("integer")
                                        .HasColumnName("onset_date_month");

                                    b2.Property<string>("Precision")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("onset_date_precision");

                                    b2.Property<int>("Year")
                                        .HasColumnType("integer")
                                        .HasColumnName("onset_date_year");
                                });

                            b1.ComplexProperty(typeof(Dictionary<string, object>), "Period", "OncoBridge.Domain.Oncology.PrimaryCancerDiagnosis.Onset#TemporalOccurrence.Period#PartialPeriod", b2 =>
                                {
                                    b2.Property<string>("Discriminator")
                                        .IsRequired()
                                        .HasMaxLength(20)
                                        .HasColumnType("character varying(20)")
                                        .HasColumnName("onset_period_kind");

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "End", "OncoBridge.Domain.Oncology.PrimaryCancerDiagnosis.Onset#TemporalOccurrence.Period#PartialPeriod.End#PartialDate", b3 =>
                                        {
                                            b3.Property<int?>("Day")
                                                .HasColumnType("integer")
                                                .HasColumnName("onset_end_day");

                                            b3.Property<string>("Instant")
                                                .HasMaxLength(40)
                                                .HasColumnType("character varying(40)")
                                                .HasColumnName("onset_end_instant");

                                            b3.Property<int?>("Month")
                                                .HasColumnType("integer")
                                                .HasColumnName("onset_end_month");

                                            b3.Property<string>("Precision")
                                                .IsRequired()
                                                .HasMaxLength(20)
                                                .HasColumnType("character varying(20)")
                                                .HasColumnName("onset_end_precision");

                                            b3.Property<int>("Year")
                                                .HasColumnType("integer")
                                                .HasColumnName("onset_end_year");
                                        });

                                    b2.ComplexProperty(typeof(Dictionary<string, object>), "Start", "OncoBridge.Domain.Oncology.PrimaryCancerDiagnosis.Onset#TemporalOccurrence.Period#PartialPeriod.Start#PartialDate", b3 =>
                                        {
                                            b3.Property<int?>("Day")
                                                .HasColumnType("integer")
                                                .HasColumnName("onset_start_day");

                                            b3.Property<string>("Instant")
                                                .HasMaxLength(40)
                                                .HasColumnType("character varying(40)")
                                                .HasColumnName("onset_start_instant");

                                            b3.Property<int?>("Month")
                                                .HasColumnType("integer")
                                                .HasColumnName("onset_start_month");

                                            b3.Property<string>("Precision")
                                                .IsRequired()
                                                .HasMaxLength(20)
                                                .HasColumnType("character varying(20)")
                                                .HasColumnName("onset_start_precision");

                                            b3.Property<int>("Year")
                                                .HasColumnType("integer")
                                                .HasColumnName("onset_start_year");
                                        });

                                    b2.HasDiscriminator<string>("Discriminator").HasValue("PartialPeriod");
                                });

                            b1.HasDiscriminator<string>("Discriminator").HasValue("TemporalOccurrence");
                        });

                    b.ComplexProperty(typeof(Dictionary<string, object>), "RecordedDate", "OncoBridge.Domain.Oncology.PrimaryCancerDiagnosis.RecordedDate#PartialDate", b1 =>
                        {
                            b1.Property<int?>("Day")
                                .HasColumnType("integer")
                                .HasColumnName("recorded_date_day");

                            b1.Property<string>("Instant")
                                .HasMaxLength(40)
                                .HasColumnType("character varying(40)")
                                .HasColumnName("recorded_date_instant");

                            b1.Property<int?>("Month")
                                .HasColumnType("integer")
                                .HasColumnName("recorded_date_month");

                            b1.Property<string>("Precision")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("character varying(20)")
                                .HasColumnName("recorded_date_precision");

                            b1.Property<int>("Year")
                                .HasColumnType("integer")
                                .HasColumnName("recorded_date_year");
                        });

                    b.HasKey("Id");

                    b.HasIndex("BatchId")
                        .HasDatabaseName("ix_primary_cancer_diagnosis_batch_id");

                    b.HasIndex("PatientId")
                        .HasDatabaseName("ix_primary_cancer_diagnosis_patient_id");

                    b.ToTable("primary_cancer_diagnosis", (string)null);
                });

            modelBuilder.Entity("OncoBridge.Domain.Oncology.StageCategory", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("Axis")
                        .IsRequired()
                        .HasMaxLength(1)
                        .HasColumnType("character varying(1)")
                        .HasColumnName("axis");

                    b.Property<Guid>("SourceResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_resource_id");

                    b.Property<Guid>("StagingId")
                        .HasColumnType("uuid")
                        .HasColumnName("staging_id");

                    b.ComplexProperty(typeof(Dictionary<string, object>), "Code", "OncoBridge.Domain.Oncology.StageCategory.Code#CodedConcept", b1 =>
                        {
                            b1.IsRequired();

                            b1.Property<string>("Code")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("character varying(200)")
                                .HasColumnName("code_code");

                            b1.Property<string>("Display")
                                .HasMaxLength(1000)
                                .HasColumnType("character varying(1000)")
                                .HasColumnName("code_display");

                            b1.Property<string>("System")
                                .IsRequired()
                                .HasMaxLength(500)
                                .HasColumnType("character varying(500)")
                                .HasColumnName("code_system");
                        });

                    b.HasKey("Id");

                    b.HasIndex("SourceResourceId")
                        .HasDatabaseName("ix_stage_category_source_resource_id");

                    b.HasIndex("StagingId", "Axis")
                        .IsUnique()
                        .HasDatabaseName("ux_stage_category_staging_axis");

                    b.ToTable("stage_category", (string)null);
                });

            modelBuilder.Entity("OncoBridge.Domain.Provenance.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BundleType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bundle_type");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_count");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<DateTimeOffset?>("NormalizedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("normalized_at");

                    b.Property<string>("NormalizerVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalizer_version");

                    b.Property<byte[]>("RawPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<string>("SourceSystemLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_system_label");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_import_batch_content_hash");

                    b.ToTable("import_batch", (string)null);
                });

            modelBuilder.Entity("OncoBridge.Domain.Provenance.Lineage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DomainEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_entity_id");

                    b.Property<string>("DomainEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("domain_entity_type");

                    b.Property<string>("FieldPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("field_path");

                    b.Property<Guid>("SourceResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_resource_id");

                    b.Property<string>("TransformationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transformation_name");

                    b.Property<string>("TransformationVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transformation_version");

                    b.HasKey("Id");

                    b.HasIndex("SourceResourceId");

                    b.HasIndex("DomainEntityType", "DomainEntityId")
                        .HasDatabaseName("ix_lineage_domain_entity");

                    b.ToTable("lineage", (string)null);
                });

            modelBuilder.Entity("OncoBridge.Domain.Provenance.SourceResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<int>("EntryIndex")
                        .HasColumnType("integer")
                        .HasColumnName("entry_index");

                    b.Property<string>("FullUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("full_url");

                    b.Property<string>("ResourceJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("resource_json");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<string>("SourceLogicalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_logical_id");

                    b.HasKey("Id");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("ix_source_resource_resource_type");

                    b.HasIndex("BatchId", "EntryIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_source_resource_batch_entry_index");

                    b.ToTable("source_resource", (string)null);
                });

            modelBuilder.Entity("OncoBridge.Domain.Oncology.CancerStaging", b =>
                {
                    b.HasOne("OncoBridge.Domain.Provenance.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cancer_staging_batch");

                    b.HasOne("OncoBridge.Domain.Oncology.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cancer_staging_patient");

                    b.HasOne("OncoBridge.Domain.Oncology.PrimaryCancerDiagnosis", null)
                        .WithMany()
                        .HasForeignKey("PrimaryCancerDiagnosisId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cancer_staging_primary_cancer_diagnosis");
                });

            modelBuilder.Entity("OncoBridge.Domain.Oncology.CancerSurgicalProcedure", b =>
                {
                    b.HasOne("OncoBridge.Domain.Provenance.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cancer_surgical_procedure_batch");

                    b.HasOne("OncoBridge.Domain.Oncology.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_cancer_surgical_procedure_patient");
                });

            modelBuilder.Entity("OncoBridge.Domain.Oncology.Patient", b =>
                {
                    b.HasOne("OncoBridge.Domain.Provenance.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_patient_batch");
                });

            modelBuilder.Entity("OncoBridge.Domain.Oncology.PrimaryCancerDiagnosis", b =>
                {
                    b.HasOne("OncoBridge.Domain.Provenance.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_primary_cancer_diagnosis_batch");

                    b.HasOne("OncoBridge.Domain.Oncology.Patient", null)
                        .WithMany()
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_primary_cancer_diagnosis_patient");
                });

            modelBuilder.Entity("OncoBridge.Domain.Oncology.StageCategory", b =>
                {
                    b.HasOne("OncoBridge.Domain.Provenance.SourceResource", null)
                        .WithMany()
                        .HasForeignKey("SourceResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_category_source_resource");

                    b.HasOne("OncoBridge.Domain.Oncology.CancerStaging", null)
                        .WithMany("Categories")
                        .HasForeignKey("StagingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_stage_category_staging");
                });

            modelBuilder.Entity("OncoBridge.Domain.Provenance.Lineage", b =>
                {
                    b.HasOne("OncoBridge.Domain.Provenance.SourceResource", null)
                        .WithMany()
                        .HasForeignKey("SourceResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineage_source_resource");
                });

            modelBuilder.Entity("OncoBridge.Domain.Provenance.SourceResource", b =>
                {
                    b.HasOne("OncoBridge.Domain.Provenance.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_resource_batch");
                });

            modelBuilder.Entity("OncoBridge.Domain.Oncology.CancerStaging", b =>
                {
                    b.Navigation("Categories");
                });
#pragma warning restore 612, 618
        }
    }
}
