// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;
using OncoBridge.Infrastructure.Persistence;

#nullable disable

namespace OncoBridge.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(OncoBridgeDbContext))]
    [Migration("20260815221209_InitialProvenanceSchema")]
    partial class InitialProvenanceSchema
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("OncoBridge.Domain.Provenance.ImportBatch", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<string>("BundleType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("bundle_type");

                    b.Property<string>("ContentHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<int>("EntryCount")
                        .HasColumnType("integer")
                        .HasColumnName("entry_count");

                    b.Property<string>("FileName")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("file_name");

                    b.Property<string>("NormalizerVersion")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("normalizer_version");

                    b.Property<byte[]>("RawPayload")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("raw_payload");

                    b.Property<DateTimeOffset>("ReceivedAt")
                        .HasColumnType("timestamptz")
                        .HasColumnName("received_at");

                    b.Property<string>("SourceSystemLabel")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_system_label");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("status");

                    b.HasKey("Id");

                    b.HasIndex("ContentHash")
                        .HasDatabaseName("ix_import_batch_content_hash");

                    b.ToTable("import_batch", (string)null);
                });

            modelBuilder.Entity("OncoBridge.Domain.Provenance.Lineage", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("DomainEntityId")
                        .HasColumnType("uuid")
                        .HasColumnName("domain_entity_id");

                    b.Property<string>("DomainEntityType")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("domain_entity_type");

                    b.Property<string>("FieldPath")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)")
                        .HasColumnName("field_path");

                    b.Property<Guid>("SourceResourceId")
                        .HasColumnType("uuid")
                        .HasColumnName("source_resource_id");

                    b.Property<string>("TransformationName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("transformation_name");

                    b.Property<string>("TransformationVersion")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)")
                        .HasColumnName("transformation_version");

                    b.HasKey("Id");

                    b.HasIndex("SourceResourceId");

                    b.HasIndex("DomainEntityType", "DomainEntityId")
                        .HasDatabaseName("ix_lineage_domain_entity");

                    b.ToTable("lineage", (string)null);
                });

            modelBuilder.Entity("OncoBridge.Domain.Provenance.SourceResource", b =>
                {
                    b.Property<Guid>("Id")
                        .HasColumnType("uuid")
                        .HasColumnName("id");

                    b.Property<Guid>("BatchId")
                        .HasColumnType("uuid")
                        .HasColumnName("batch_id");

                    b.Property<string>("ContentHash")
                        .HasMaxLength(64)
                        .HasColumnType("character varying(64)")
                        .HasColumnName("content_hash");

                    b.Property<int>("EntryIndex")
                        .HasColumnType("integer")
                        .HasColumnName("entry_index");

                    b.Property<string>("FullUrl")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)")
                        .HasColumnName("full_url");

                    b.Property<string>("ResourceJson")
                        .HasColumnType("jsonb")
                        .HasColumnName("resource_json");

                    b.Property<string>("ResourceType")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)")
                        .HasColumnName("resource_type");

                    b.Property<string>("SourceLogicalId")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)")
                        .HasColumnName("source_logical_id");

                    b.HasKey("Id");

                    b.HasIndex("ResourceType")
                        .HasDatabaseName("ix_source_resource_resource_type");

                    b.HasIndex("BatchId", "EntryIndex")
                        .IsUnique()
                        .HasDatabaseName("ux_source_resource_batch_entry_index");

                    b.ToTable("source_resource", (string)null);
                });

            modelBuilder.Entity("OncoBridge.Domain.Provenance.Lineage", b =>
                {
                    b.HasOne("OncoBridge.Domain.Provenance.SourceResource", null)
                        .WithMany()
                        .HasForeignKey("SourceResourceId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_lineage_source_resource");
                });

            modelBuilder.Entity("OncoBridge.Domain.Provenance.SourceResource", b =>
                {
                    b.HasOne("OncoBridge.Domain.Provenance.ImportBatch", null)
                        .WithMany()
                        .HasForeignKey("BatchId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired()
                        .HasConstraintName("fk_source_resource_batch");
                });
#pragma warning restore 612, 618
        }
    }
}
