/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

export interface LineageResponse {
  domainEntityId: string;
  domainEntityType: string;
  fieldPath?: (string | null);
  sourceResourceId: string;
  transformationName: string;
  transformationVersion: string;
}
