/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PartialDateResponse } from '../models/partial-date-response';
export interface PartialPeriodResponse {
  end?: (null | PartialDateResponse);
  start?: (null | PartialDateResponse);
}
