/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { LineageResponse } from '../models/lineage-response';
export interface ProvenanceResponse {
  domainEntityId: string;
  records: Array<LineageResponse>;
}
