/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CodedConceptResponse } from '../models/coded-concept-response';
export interface StageCategoryResponse {
  axis: string;
  code: CodedConceptResponse;
  sourceResourceId: string;
}
