/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CodedConceptResponse } from '../models/coded-concept-response';
import { StageCategoryResponse } from '../models/stage-category-response';
export interface TimelineStagingDetailResponse {
  categories: Array<StageCategoryResponse>;
  stageGroup?: (null | CodedConceptResponse);
}
