/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { PartialDateResponse } from '../models/partial-date-response';
import { TemporalOccurrenceResponse } from '../models/temporal-occurrence-response';
import { TimelineDiagnosisDetailResponse } from '../models/timeline-diagnosis-detail-response';
import { TimelineProcedureDetailResponse } from '../models/timeline-procedure-detail-response';
import { TimelineStagingDetailResponse } from '../models/timeline-staging-detail-response';
export interface TimelineEventResponse {
  anchor?: (null | PartialDateResponse);
  anchorSource?: (string | null);
  diagnosis?: (null | TimelineDiagnosisDetailResponse);
  entityId: string;
  entityKind: string;
  label: string;
  occurrence?: (null | TemporalOccurrenceResponse);
  procedure?: (null | TimelineProcedureDetailResponse);
  staging?: (null | TimelineStagingDetailResponse);
}
