/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { CodedConceptResponse } from '../models/coded-concept-response';
import { PartialDateResponse } from '../models/partial-date-response';
export interface TimelineDiagnosisDetailResponse {
  code: CodedConceptResponse;
  recordedDate?: (null | PartialDateResponse);
}
