/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TimelineEventResponse } from '../models/timeline-event-response';
export interface TimelineGroupResponse {
  events: Array<TimelineEventResponse>;
  kind: string;
  sequence: (number | string);
}
