/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { TimelineEventResponse } from '../models/timeline-event-response';
export interface UnsequencedTimelineEventResponse {
  event: TimelineEventResponse;
  reason: string;
}
