/* eslint-disable */
/* Code generated by ng-openapi-gen DO NOT EDIT. */

import { HttpClient, HttpContext, HttpResponse } from '@angular/common/http';
import { Observable } from 'rxjs';
import { filter, map } from 'rxjs/operators';
import { StrictHttpResponse } from '../../strict-http-response';
import { RequestBuilder } from '../../request-builder';

import { PatientRecordResponse } from '../../models/patient-record-response';

export interface GetPatientRecord$Params {
  patientId: string;
}

export function getPatientRecord(http: HttpClient, rootUrl: string, params: GetPatientRecord$Params, context?: HttpContext): Observable<StrictHttpResponse<PatientRecordResponse>> {
  const rb = new RequestBuilder(rootUrl, getPatientRecord.PATH, 'get');
  if (params) {
    rb.path('patientId', params.patientId, {});
  }

  return http.request(
    rb.build({ responseType: 'json', accept: 'application/json', context })
  ).pipe(
    filter((r: any): r is HttpResponse<any> => r instanceof HttpResponse),
    map((r: HttpResponse<any>) => {
      return r as StrictHttpResponse<PatientRecordResponse>;
    })
  );
}

getPatientRecord.PATH = '/api/v1/patients/{patientId}/record';
